#!/bin/bash

# -------------------------------
# Nexus 3.77.2-02 + Java 17 Setup
# -------------------------------

set -e

echo "=== Step 1: Installing Java 17 ==="
sudo yum clean metadata
sudo yum install java-17-amazon-corretto -y
java -version

echo "=== Step 2: Creating /opt directory and navigating ==="
cd /opt

echo "=== Step 3: Downloading Nexus 3.77.2-02 ==="
sudo wget https://download.sonatype.com/nexus/3/nexus-3.77.2-02-unix.tar.gz

echo "=== Step 4: Extracting Nexus Archive ==="
sudo tar -xvf nexus-3.77.2-02-unix.tar.gz

echo "=== Step 5: Renaming Nexus Folder ==="
sudo mv nexus-3.77.2-02 nexus

echo "=== Step 6: Creating Nexus User ==="
sudo adduser nexus || echo "User nexus already exists"

echo "=== Step 7: Changing Ownership ==="
sudo chown -R nexus:nexus /opt/nexus
sudo chown -R nexus:nexus /opt/sonatype-work

echo "=== Step 8: Configuring run_as_user ==="
echo 'run_as_user="nexus"' | sudo tee /opt/nexus/bin/nexus.rc

echo "=== Step 9: Creating systemd service file ==="
sudo tee /etc/systemd/system/nexus.service > /dev/null <<EOF
[Unit]
Description=Nexus service
After=network.target

[Service]
Type=forking
LimitNOFILE=65536
User=nexus
Group=nexus
ExecStart=/opt/nexus/bin/nexus start
ExecStop=/opt/nexus/bin/nexus stop
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOF


sudo yum install firewalld -y
sudo systemctl enable firewalld
sudo systemctl start firewalld


echo "=== Step 12: Opening Port 8081 ==="
sudo firewall-cmd --permanent --zone=public --add-port=8081/tcp
sudo firewall-cmd --reload

echo "=== Step 10: Enabling Nexus Service ==="
sudo systemctl enable nexus

echo "=== Step 11: Starting Nexus Service ==="
sudo systemctl start nexus
echo "=== Step 11: status Nexus service ==="
sudo systemctl status nexus

echo "=== Installation Complete! ==="
echo "Password file"
sudo cat /opt/sonatype-work/nexus3/admin.password
